version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ai-interview-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_interview
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data:
